In [2]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
start_column = 7    # マトリックスの開始列（G列）
start_row = 5       # マトリックスの開始行（5行）
num = 19            # 読み取るセルの範囲（num 行の正方形を読み取る）

In [5]:
# 階層構造を定義した2次元マトリックスを取得する関数
def read_data(start_row, start_column, num):
    df = pd.read_excel("機能項目相互間の関係.xlsx", header=None, sheet_name="機能項目相互間の関係", 
                       skiprows=start_row - 1, nrows=num, usecols=range(start_column - 1, start_column - 1 + num))
    
    data = np.where(df.values == "○", 1, 0)

    return data

# データを読み取る
matrix = read_data(start_row, start_column, num)
matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1],
       [0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0,

In [6]:
# ISM機能階層分析を行う関数
def ism_FHA(matrix):

    ###----------可達行列作成処理----------###
    # 行列のサイズを取得
    n = len(matrix)

    print('\n----------隣接行列----------')
    matrix = matrix.astype(bool)
    I = np.eye(n).astype(bool)
    adj_matrix = np.logical_or(matrix, I)
    print(adj_matrix.astype(int))

    print('\n----------可達行列----------')
    reachability_matrix = adj_matrix.copy()
    while not np.array_equal(reachability_matrix, reachability_matrix @ adj_matrix):
        reachability_matrix = reachability_matrix @ adj_matrix  #@演算子を利用することで行列積を求める（bool演算）
    print(reachability_matrix.astype(int))

    return reachability_matrix

# 指定した行と列を削除する関数
def remove_rows_and_columns(matrix, rows_to_remove):
    matrix = np.delete(matrix, rows_to_remove, axis=0)
    matrix = np.delete(matrix, rows_to_remove, axis=1)
    return matrix

# Trueが1つだけ含まれている行を探す関数
def find_single_true_row(matrix):
    single_true_rows = []
    for i in range(len(matrix)):
        if np.sum(matrix[i]) == 1:
            single_true_rows.append(i)
    return single_true_rows

# Ri記録

# Ai記録

# RiかつAi

# RiかつAi=Ri

In [7]:
# 可達行列導出
reachability_matrix = ism_FHA(matrix)


----------隣接行列----------
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1]
 [1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1]
 [1 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1]
 [1 1 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 1 1]
 [1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1]
 [0 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]

----------可達行列----------
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1]
 [1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1]
 [1 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1]
 [1 

In [49]:
# 0と1で構成される行列を作成 (サンプル行列)
matrix = np.array([
    [1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0],
    [1, 1, 1, 0, 1],
    [1, 1, 1, 1, 0],
    [1, 1, 1, 0, 1]
])

In [50]:
# 各行で1になっている位置を特定し、リストで表示
Ri = []
for i in range(matrix.shape[0]):  # 行数
    row_positions = [j for j in range(matrix.shape[1]) if matrix[i][j] == 1]
    Ri.append(row_positions)

print(Ri)

[[0], [0, 1], [0, 1, 2, 4], [0, 1, 2, 3], [0, 1, 2, 4]]


In [51]:
# 行列を転置して各列で1になっている位置を特定
transposed_matrix = matrix.T
Ai = []
for j in range(transposed_matrix.shape[0]):  # 列数
    column_positions = [i for i in range(transposed_matrix.shape[1]) if transposed_matrix[j][i] == 1]
    Ai.append(column_positions)

print(Ai)

[[0, 1, 2, 3, 4], [1, 2, 3, 4], [2, 3, 4], [3], [2, 4]]


In [52]:
# 各リストから位置ごとに共通する数字を取り出す
R_and_A = []
for i in range(min(len(Ri), len(Ai))):
    common_elements = list(set(Ri[i]) & set(Ai[i]))
    R_and_A.append(common_elements)

print(R_and_A)

[[0], [1], [2, 4], [3], [2, 4]]


In [53]:
R_and_A_R = []
delete = []

for i in range(min(len(Ri), len(R_and_A))):
    if Ri[i] == R_and_A[i]:
        R_and_A_R.append(Ri[i])
        delete.append(i)

print(R_and_A_R)
print(delete)

[[0]]
[0]


In [54]:
# 特定の数値を削除
for row in Ri:
    for value in delete:
        while value in row:
            row.remove(value)
    
print(Ri)

[[], [1], [1, 2, 4], [1, 2, 3], [1, 2, 4]]
